### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by saomair** [mgp25/WhatsApp-Tools#1]
Can you please check this is not working i just checked 

also your website is not working as well 

http://www.watools.es/perfil.php

**Comment by mgp25** [comment]
@saomair update it with https://github.com/WHAnonymous/Chat-API

**Comment by saomair** [comment]
Thank you @mgp25

**Comment by MuhammadBilalTariq** [comment]
Yes, I have checked too and it is not working fo[r ](gbapk .info/gbwhatsapp-2021)me also.
